### PR TITLE
feat-added avator and badges components

### PR DESCRIPTION
**Pull request by manish591**

### CODE REVIEW

**Review by ravikumar1002 — APPROVED** [review]
hey Manish everything looks good , but in html code I have a doubt that I read somewhere that after ul tag, li will be next tag but in your code I saw that ul>a>li,  you have used .
Is this good approach?  (I'm not quite sure about this)

**Review by romabulani — COMMENTED** [review]
Hi Manish, Everything looks good.

- Same as Ravi's comment regarding `<a>` inside `<ul>`,  just check it once.
- The avatar spelling you have kept it deliberately, if yes then its fine

**Comment by manish591** [comment]
I am looking into it.

**Comment by manish591** [comment]
Hey Roma, I have made changes to the markup. I found on the web that it is recommended to use li as a direct child of ul.
Could you please look into this.

**Review by romabulani — APPROVED** [review]
Hi Manish,
Understood.

**Pull request merged**
