### PR TITLE
Added cards component

### PR DESCRIPTION
**Pull request by manish591**

### CODE REVIEW

**Review by Sharmaa-Ansh — COMMENTED** [review]
Try putting media queries using rems

**Review by varnita619 — APPROVED** [review]
Everything looks good and clean

**Comment by manish591** [comment]
> 

But is it necessary?

**Comment by vinc3nati** [comment]
It's like you are calling add(num1, num2) with only num1

**Comment by manish591** [comment]
> It's like you are calling add(num1, num2) with only num1

But why we should use rems and not pixels

**Comment by vinc3nati** [comment]
Oh, so you were referring to that, I was referring to my change request! But as far your question goes, `rems` makes it a lot easier to adjust to different screen sizes without media queries, so it is advised to use `rem` wherever possible. Though `px` can be used in small values like `border: 1px solid #000`, etc.

**Review by romabulani — APPROVED** [review]
good to merge

**Pull request merged**
